# Generated by Django 4.2.7 on 2023-11-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса:')),
                ('instructor', models.CharField(max_length=255, verbose_name='Преподаватель курса:')),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за месяц:')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
