# Generated by Django 4.2.7 on 2023-11-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdtick', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterField(
            model_name='products',
            name='names',
            field=models.CharField(max_length=60, verbose_name='Цена'),
        ),
    ]
